name: Node.js CI

on: [push]


defaults:
  run:
    working-directory: apis/userprofile

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "Build Error";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Workflow ${{ github.run_number }} Failed! ",
            body: body
          }); 
 
    - uses: azure/docker-login@v1
      with:
         login-server: ${{secrets.AZ_CONTAINER_HOST}}
         username: ${{secrets.AZ_CONTAINER_USERNAME}}
         password: ${{secrets.AZ_CONTAINER_PWD}}

    - run: |
          docker build . -t openhackm2c9dk93acr.azurecr.io/devopsoh/api-userprofile:v4
          docker push openhackm2c9dk93acr.azurecr.io/devopsoh/api-userprofile:v4
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'userprofile-staging'
        images: 'openhackm2c9dk93acr.azurecr.io/devopsoh/api-userprofile:v4' 
