name: Node.js CI

on: [push]


defaults:
  run:
    working-directory: apis/userprofile

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "error";
          github. issues.create({
            owner! context.repo. owner.
            repo: context.repo. repo.
            title: "$t env.buitename}} Workflow ${{ github.run_number }} Failed! ".
            body: body
          });  
          
